name: 'CMake Build/Test'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # [Manual triggers with workflow_dispatch](
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
  workflow_dispatch:
  
jobs:
  build:
    name: Self-hosted Runner
    runs-on: [self-hosted, x64]
    strategy:
      matrix:
        os: [Linux, Windows]
        
        include:
          - os: Linux
            cmake_preset: ci-linux
          - os: Windows
            cmake_preset: ci-windows
    env:
      PYTHON_VERSION: "3.10"

    steps:
    - name: Install basic dependencies on ${{matrix.os}}
      if: matrix.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y g++-11 clang-14 ccache gettext

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Python dependencies like Conan package manager etc.
      run: |
        python -m pip install --upgrade pip
        pip --disable-pip-version-check --no-cache-dir install conan
        conan profile new --detect --force default > /dev/null
        # Conan detects a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
        # 'libstdc++' for backwards compatibility. Our compiler is using the new CXX11 ABI 
        # by default (libstdc++11).
        conan profile update settings.compiler.libcxx=libstdc++11 default
        # C++20 standard
        conan profile update settings.compiler.cppstd=20 default
        # install other packages
        if [ -f requirements.txt ]; then pip --disable-pip-version-check --no-cache-dir install -r requirements.txt; fi

    - name: Install CMake and ninja
      uses: lukka/get-cmake@v3.23.0

    - name: Version info of tools used
      run: |
        lsb_release -a
        g++ --version
        clang++ --version
        ccache --version
        python --version
        conan  --version
        cmake --version
        ninja --version

    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup ccache Compiler Cache
      if: matrix.os == 'Linux'
      uses: hendrikmuhs/ccache-action@v1.2.2

    - name: Configure and Build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{ matrix.cmake_preset }}
        buildPreset: ${{ matrix.cmake_preset }}

    - name: Build l10n
      if: matrix.os == 'Linux'
      run: |
        cmake --build --preset ${{ matrix.cmake_preset }} --target l10n
      
    - name: Run Unit Test
      run: |
        ctest --preset ${{ matrix.cmake_preset }}
