name: FOSSA

on:
  push:
    # branches: [ main ]
  pull_request:
    # branches: [ main ]
  # [Manual triggers with workflow_dispatch](
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/)
  workflow_dispatch:

jobs:
  fossa-scan:
    name: Fossa Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: FOSSA analysis
        uses: fossas/fossa-action@main
        with:
          api-key:  ${{ secrets.FOSSA_API_KEY }}
