name: 'SpellCheck Actions'

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  spellcheck:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Ensure proper Python version
      uses: actions/setup-python@v5
      with: { python-version: "3.12" }
  
    - name: Install CodeSpell
      run: pip3 install codespell

    - name: CodeSpell check
      continue-on-error: true
      run: cmake -P cmake/codespell.cmake

    - name: Gather Markdown files from git for PySpelling
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#multiline-strings
      # echo "MARKDOWN_FILES=$(git ls-files '*.md')" >> $GITHUB_ENV
      run: |
        {
          echo 'MARKDOWN_FILES<<EOF'
          git ls-files '*.md'
          echo EOF
        } >> "$GITHUB_ENV"

    - name: Show Markdown files for PySpelling
      run: |
        echo "Markdown: ${{ env.MARKDOWN_FILES }}"

    - name: PySpelling [Markdown]
      id: spellcheck
      uses: rojopolis/spellcheck-github-actions@0.47.0
      continue-on-error: true
      with:
        config_path: .github/config/spellcheck.yml
        source_files: ${{ env.MARKDOWN_FILES }}
        task_name: Markdown
        output_file: spellcheck-output.txt

    - name: Upload PySpelling Artifact
      uses: actions/upload-artifact@v4
      if: '!cancelled()' # Do not upload artifact if job was cancelled
      with:
        name: Spellcheck Output
        path: spellcheck-output.txt
